---
- name: "Create containerd.conf"
  ansible.builtin.copy:
    dest: "/etc/sysctl.d/containerd.conf"
    content: |
      overlay
      br_netfilter

- name: "Add docker repository"
  ansible.builtin.copy:
    dest: "/etc/yum.repos.d/docker.repo"
    content: |
      [docker-ce-stable]
      name=Docker CE Stable - $basearch
      baseurl=https://download.docker.com/linux/centos/$releasever/$basearch/stable
      enabled=1
      gpgcheck=1
      gpgkey=https://download.docker.com/linux/centos/gpg
  
- name: "Install containerd.io"
  ansible.builtin.package:
    name: containerd.io
    update_cache: true
    state: present

- name: "Start and Enable containerd service"
  ansible.builtin.systemd_service:
    name: containerd
    enabled: true
    state: started

- name: "Create config.toml"
  ansible.builtin.shell: containerd config default > /etc/containerd/config.toml

- name: "Set SystemdCgroup"
  lineinfile:
    path: /etc/containerd/config.toml
    regexp: '^SystemdCgroup'
    line: 'SystemdCgroup = true'
...