---
- name: "Get join command"
  ansible.builtin.shell: kubeadm token create --print-join-command
  register: joinCmd_output
  when: inventory_hostname == groups['master'][0]

- name: "Join slaves to cluster"
  ansible.builtin.shell: "{{ hostvars[groups['master'][0]].joinCmd_output.stdout }}"
  when: inventory_hostname in groups['slaves']
...